[meta]
name = "Hackers & Tech Culture"

[content]
feeds = [
  {name = "Paulie G.", uri = "http://www.aaronsw.com/2002/feeds/pgessays.rss"},
  {name = "The Digital Antiquarian", uri = "https://www.filfre.net/feed/rss/"},
  {name = "Denny Britz", uri = "https://dennybritz.com/rss.xml"},
]
